---
title: Reading Notes - ENGR392 
author: Adrien Tremblay
output: pdf_document
---

# Reading - Do obhects have politics?
* Can an object be inherintly good or bad?
* *Politics* - arragements of power and authority in human      associations.
* Can be used to enhance power of some people.
* Objects can exert political will on people and have           politics in them* Though objects are neutral what if some       are designed for some specific purpose?.
* Technology create inequality?
* View1: The adoption of a technology requires the creating     of a specific set of social conditions
+ Nuclear power plants require techo-scientific elite
* View 2: Technologies are strongly compatibale with            certain social and political relationships but are not          absolutely necessary.
+ Solar energy does not *require* democracy.
* There are both internal and external views on artifact        politics.
+ Inside the system or outside it.
+ Democracy stops at the factory gate
* Shpuld we redistribute wealth, have broder public             participation or stronger centralized public and private        management.
* Centralized systems and dangerous tech(like plutonium)        motivate the government to invade privacy.
* When adopting a new technology:
+ Are there alternatives?
+ Will social groups change the tech's political              implications?
* Author says we should focus on both the technical object      itself and the context the object is situated.
* It is harder to justify changes in society politically


# Reading - How Technology is Destorying Jobs
* Tech behind low jobs.
* Graph of Productivity vs Total jobs converged during the 2000's.
* Productivity rising but income is the same.
* Job market shifting
* What is the true cause of the lackluster job market?
* YOu need more educayshun.
* *Will the job market work out?*
* Some tasks need humans
* Automation can help young companies.

# Reading - The Automation Charade
* Does new tech really improve the lives of housewives?
+ Or bring more work?
* Tech is not destorying jobs but shifting the job market.
+ Robots must work with humans.
* The power of robots has been exaggerated.
+ And used to fearmonger by corperations.

# Reading May 25 - How We Treat Women by Kyle Edwards
* Man camps increace accounts of sexual assaults.
* Hyper masculine rigger mentality.
* Often women don't report their assaults.
* This sexual harrassement has been going on for a long time.
* Reporting to the company doesn't do anything.

# Reading May 25 - Doing Domestic Time by Wajcman
* Is work simply shifting?
* Wife expected to do all household work.
* Wives still spending a fuck ton of time.
* Why are we doing things indipendantly in each household?
  + Communal thing failed.
* Certain tasks are manly and others womanly.
  + The womanly ones are more regular.
* Time spent remains constant due to rising expectations.
* Domestic energy use risen dramatically.
* Use of technology changing too.
  + Bathtubs.
  + People bath too much and power shower.
* Tech is transfered from industry to the home?
  + Not well attuned.
  + Washing machine, Fridge, Gas, Electricity, etc...
  + No one to mesure efficiency?
* Parents invest more time in children.
* Dads do the fun stuff with their kids.
* Activities happen simultaniously.
* Domestic work is harder to automate and more emotional.
* Robots can take care of us.  But do not care about us.
* People misuse the time saved with other gadgets.

# Reading May 27 - United Nations Free, Prior and Informed Consent of Indigenous Peoples.
* Must have conscent of indigenous people for things that affect them.
* Reperations.g
  + If no free prior informed conscent.
* No discrimination.
* Cultural practice.
* *Free* means no coersion or manipulation.
* Indigenous peoples to be informed of everything.
* Local leaders must be consulted.
* This consent must be verified.
* Government cannot be held accountable to itself.
* Cooperate in good faith.
* Conscent must be the approval for consultation.
* Treaty norms must be respected as well as the right to self-determination.
  + Right to maintain culture.

# Reading May 27 - Injunctions have only served to prove the point: Canada is a smash-and-grab country for industry
* Injunctions allow companies (Like Coastal Gaslink) to have cops come and break blockades/protests.
* Too much power.
* Political weapon.
* Premtive.

# Reading May 27 - Code Is Law
* Each age has a threat to liberty and a regulator.
* Age of cyberspace, regulator is code?
* Internet will go from place of freedom to opression.

# Readings June 3

## Notes on Design Justice and Digital Technologies
* Digital tech has changed politics.
* It can be used for good.
* but also evil.
* Design should democratically involve everyone.

## Energy for whom and for what?
* Renewable energy projects can have negative affects on the population.
* Decentralization: using local resources.
